# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 05:38
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='\uc774\ub984')),
                ('is_staff', models.BooleanField(default=False, verbose_name='\uc2a4\ud0dc\ud504 \uad8c\ud55c')),
                ('phone', models.CharField(max_length=140, null=True, verbose_name='\ud578\ub4dc\ud3f0 \ubc88\ud638')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='\uc0dd\uc77c')),
                ('is_active', models.BooleanField(default=True, verbose_name='\uc0ac\uc6a9\uc911')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\uac00\uc785\uc77c')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
