# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200206_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='\uc0dd\uc77c (ex: 1990-07-14)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=140, null=True, verbose_name='\ud578\ub4dc\ud3f0 \ubc88\ud638 (ex: 010-1234-5678)'),
        ),
    ]
