# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, verbose_name='\uc81c\ubaa9')),
                ('content', models.TextField(verbose_name='\ub0b4\uc6a9')),
                ('auther', models.CharField(max_length=16, verbose_name='\uc791\uc131\uc790')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\uc791\uc131\uc77c')),
            ],
        ),
    ]
