# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200204_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\uc791\uc131\uc77c'),
        ),
    ]
