# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20200211_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='article_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
