# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_article_anonymous_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=16, verbose_name='\uc791\uc131\uc790'),
        ),
    ]
