# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-19 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20200213_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='anonymous_author',
        ),
    ]
